### ISSUE TITLE
Keep compliant with bxmp syntax

### ISSUE THREAD

**Issue by RonDingDing** [xenanetworks/open-automation-python-api#41]
On my way of making 3918, I found that you can pass in a stream id into P_TRAFFIC.
![image](https://user-images.githubusercontent.com/28916409/183555734-07ef5f1d-b08e-4676-90c3-d1459715c61a.png)
After getting the message bytes using my own driver, it shows:
```
{"timestamp": "8/09/2022 9:47:09.005 上午","content": ["58","45","4E","41","00","01","00","01","03","7C","05","00","00","00","02","EC","00","00","00","00","01","00","00","00"]},
```
"00","01","00","01", means 1 byte of index value, 1 byte of actual value
So it will be translated into:
8/09/2022 10:58:52.852 上午 | 5   2   [0]        748   P_TRAFFIC                 P_TRAFFIC                 COMMAND_VALUE P_TRAFFIC.SetDataAttr(on_off=StartOrStop.START)

having a stream value of [0]

Is this a bug or a feature? Do we need to change the xoa-driver with it?

**Comment by RonDingDing** [comment]
@leonardhyu Does this means the xoa-driver doesn't need to change? Artem and me think like this.

**Comment by leonardhyu** [comment]
@RonDingDing yes, you are right.
