### ISSUE TITLE
🐛[BUG] PEF_VALUE and PEF_MASK should have three indices not two

### ISSUE THREAD

**Issue by leonardhyu** [xenanetworks/open-automation-python-api#45]
The last one is called `protocol_segment_index`. I have added it to the LLI class, but we also need to make changes to the HLI. @ArtemConstantinov

**Comment by ArtemConstantinov** [comment]
Those indices are missing from the CLI documentation.
It is not clear from where is taken the value of ``protocol_segment_index`` it more looks like indice value user needs to set at the run time explicitly, and if it's true then the current declaration of this index on the LLI is wrong.
