### ISSUE TITLE
[🐛 Bug] port.multicast.mode.get() and port.multicast.mode_extended.get() generate errors

### ISSUE THREAD

**Issue by leonardhyu** [xenanetworks/open-automation-python-api#55]
![Image](https://user-images.githubusercontent.com/17590289/203601521-d6e12cc5-8e1c-494b-8675-2408dd1e3309.png)

PROBLEM FOUND!
It actually has nothing to do with push notification. If you query the multicast mode, you will get the same error as the customer sees. I think the xenaserver of the customer still pushes the multicast info to the client while the latest one not. But the root cause is indeed in the xoa-driver.

Either of these two are generating the error! 😄

![Image](https://user-images.githubusercontent.com/17590289/203601642-e1b54fc1-ddec-4315-b3b5-798fa49bd449.png)

**Comment by ArtemConstantinov** [comment]
The issue only presents on ``mode_extended`` the structure which is defined in xoa_driver is not match the packet we receive.
Sims like the definition of structure in driver suppose to be:
``` python
        ipv4_multicast_addresses: XmpField[xt.XmpIPV4AddressListStopToKeep4] = XmpField(xt.XmpIPV4AddressListStopToKeep4)  
        operation: XmpField[xt.XmpByte] = XmpField(xt.XmpByte, choices=MulticastExtOperation) 
        second_count: XmpField[xt.XmpByte] = XmpField(xt.XmpByte)  
        period: XmpField[xt.XmpByte] = XmpField(xt.XmpByte) # <- value missing
        igmp_version: XmpField[xt.XmpByte] = XmpField(xt.XmpByte, choices=IGMPVersion) 
```
After checking the server code sims like it is a `multicastperiod` but better to check that with the guys...
